name: Tests
on: push

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v3
        with:
          python-version: 3.11.3
        
      - name: Install tools
        run: python -m pip install --upgrade pip pytest requests flask flask_wtf flask_behind_proxy flask_sqlalchemy flask_login datetime GitPython

      - name: Test webpages
        run: python3 tests/test_basic.py

      - name: Test registration form
        run: python3 tests/test_users.py